version: '3.1'
services: 
  my-mongo-db:
    image: 'mongo'
    container_name: 'my-mongo-db'
    environment:     
      MONGO_INITDB_ROOT_USERNAME: amin 
      MONGO_INITDB_ROOT_PASSWORD: amiafu
    ports: 
      - 27017:27017
  my-mongo-express: 
    image: 'mongo-express'
    restart: always
    container_name: 'my-mongo-express'
    environment: 
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=my-mongo-db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=amin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=amiafu
      - ME_CONFIG_BASICAUTH_USERNAME=amin
      - ME_CONFIG_BASICAUTH_PASSWORD=amiafu
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    ports: 
      - 8081:8081

networks:
  default:
    external:
      name: my-mongo-network